# Generated by Django 4.0.3 on 2022-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='apply',
            field=models.BooleanField(null=True, verbose_name='Подтвердить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dataSend',
            field=models.CharField(max_length=30, verbose_name='Дата забора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fromCity',
            field=models.CharField(max_length=30, verbose_name='Город отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fromCountry',
            field=models.CharField(max_length=30, verbose_name='Страна отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.CharField(max_length=100, null=True, verbose_name='Высота посылкиы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length',
            field=models.CharField(max_length=100, null=True, verbose_name='Длина посылки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postIndexRecipient',
            field=models.CharField(max_length=30, verbose_name='Почтовый индекс получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postIndexSender',
            field=models.CharField(max_length=30, verbose_name='Почтовый индекс отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='printNeed',
            field=models.BooleanField(verbose_name='Печать'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipientAddress',
            field=models.CharField(max_length=30, verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipientName',
            field=models.CharField(max_length=30, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipientTel',
            field=models.CharField(max_length=30, verbose_name='Телефон получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sendersAddress',
            field=models.CharField(max_length=30, verbose_name='Адрес отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sendersName',
            field=models.CharField(max_length=30, verbose_name='Имя отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sendersTel',
            field=models.CharField(max_length=30, verbose_name='Телефон отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='typePackage',
            field=models.CharField(max_length=30, verbose_name='Тип посылки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(max_length=30, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='whereCity',
            field=models.CharField(max_length=30, verbose_name='Город получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='whereCountry',
            field=models.CharField(max_length=30, verbose_name='Страна отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.CharField(max_length=100, null=True, verbose_name='Ширина посылки'),
        ),
    ]
