# Generated by Django 4.0.3 on 2022-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_order_options_order_apply_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apply',
            field=models.BooleanField(verbose_name='Подтвердить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='printNeed',
            field=models.BooleanField(null=True, verbose_name='Печать'),
        ),
    ]
