# Generated by Django 4.0.3 on 2022-04-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_apply_alter_order_printneed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trackcode',
            field=models.IntegerField(default='0000000000', max_length=10, verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='order',
            name='apply',
            field=models.BooleanField(default=False, verbose_name='Подтвердить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.CharField(max_length=100, null=True, verbose_name='Высота посылки'),
        ),
    ]
