# Generated by Django 4.0.3 on 2022-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_order_apply_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=50, null=True, verbose_name='Время подтверждения'),
        ),
    ]
