# Generated by Django 4.0.3 on 2022-04-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trackcode',
            field=models.CharField(default='0000000000', max_length=30, verbose_name='Номер накладной'),
        ),
    ]
