# Generated by Django 4.0.3 on 2022-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_order_trackcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trackcode',
            field=models.IntegerField(default='0000000000', verbose_name='Номер накладной'),
        ),
    ]
