# Generated by Django 4.0.3 on 2022-05-20 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_order_invoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipmentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время передачи в DHL'),
        ),
    ]
