# Generated by Django 4.0.3 on 2022-05-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_order_shipmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postIndexRecipient',
            field=models.IntegerField(max_length=6, verbose_name='Почтовый индекс получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postIndexSender',
            field=models.IntegerField(max_length=6, verbose_name='Почтовый индекс отправителя'),
        ),
    ]
