# Generated by Django 4.0.3 on 2022-05-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_order_postindexrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instruction',
            field=models.TextField(max_length=300, null=True, verbose_name='Инструкция для курьера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(max_length=300, null=True, verbose_name='Подробное содержимое груза'),
        ),
    ]
