# Generated by Django 4.0.3 on 2022-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_order_instruction_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postIndexRecipient',
            field=models.CharField(max_length=6, verbose_name='Почтовый индекс получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postIndexSender',
            field=models.CharField(max_length=6, verbose_name='Почтовый индекс отправителя'),
        ),
    ]
