# Generated by Django 4.0.3 on 2022-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_alter_order_comment_alter_order_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPay',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время подтверждения'),
        ),
    ]
