# Generated by Django 4.0.3 on 2022-06-08 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_alter_order_shipmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipmentDateFuture',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Позднее время'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipmentDate',
            field=models.TimeField(blank=True, verbose_name='Раннее время'),
        ),
    ]
