# Generated by Django 4.0.3 on 2022-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_alter_order_shipmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipientAddress',
            field=models.CharField(max_length=1000, verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipientName',
            field=models.CharField(max_length=100, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sendersAddress',
            field=models.CharField(max_length=1000, verbose_name='Адрес отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sendersName',
            field=models.CharField(max_length=100, verbose_name='Имя отправителя'),
        ),
    ]
