# Generated by Django 4.0.3 on 2022-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_alter_order_fromcountry_alter_order_wherecountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fromCity',
            field=models.CharField(max_length=100, verbose_name='Город отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='whereCity',
            field=models.CharField(max_length=100, verbose_name='Город получателя'),
        ),
    ]
