# Generated by Django 4.0.3 on 2022-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_order_fromcity_alter_order_wherecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courierNum',
            field=models.CharField(blank=True, max_length=16, verbose_name='Номер подтверждения'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipientName',
            field=models.CharField(max_length=35, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sendersName',
            field=models.CharField(max_length=35, verbose_name='Имя отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trackcode',
            field=models.CharField(blank=True, default='0000000000', max_length=16, verbose_name='Номер накладной'),
        ),
    ]
