# Generated by Django 4.0.3 on 2022-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=30, null=True)),
                ('datefrom', models.DateTimeField(null=True)),
                ('dateto', models.DateTimeField(null=True)),
                ('procent', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
