# Generated by Django 4.0.3 on 2022-04-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='datefrom',
            field=models.DateTimeField(null=True, verbose_name='Срок начала'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='dateto',
            field=models.DateTimeField(null=True, verbose_name='Срок конца'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='procent',
            field=models.IntegerField(null=True, verbose_name='Процент снижения'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo',
            field=models.CharField(max_length=30, null=True, verbose_name='Промокод'),
        ),
    ]
