# Generated by Django 4.0.3 on 2022-05-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_coopsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopsettings',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='Текст'),
        ),
    ]
