# Generated by Django 4.0.3 on 2022-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_alter_coopsettings_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopsettings',
            name='text_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='coopsettings',
            name='text_kk',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='coopsettings',
            name='text_ru',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='coopsettings',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='coopsettings',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='coopsettings',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
