# Generated by Django 4.0.3 on 2022-05-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Файл тарифа', 'verbose_name_plural': 'Файл тарифа'},
        ),
    ]
