# Generated by Django 4.0.3 on 2022-05-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_slider_title', models.CharField(max_length=50, verbose_name='Заголовок слайда')),
                ('main_slider_text', models.CharField(max_length=50, verbose_name='Текст слайда')),
                ('main_slider_image', models.ImageField(upload_to='', verbose_name='Картинка слайда')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
