# Generated by Django 4.0.3 on 2022-05-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_slider',
            name='main_slider_image',
            field=models.ImageField(upload_to='static/img/first-screen', verbose_name='Картинка слайда'),
        ),
    ]
