# Generated by Django 4.0.3 on 2022-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_main_slider_main_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50, verbose_name='Заголовок О нас')),
                ('about_text', models.CharField(max_length=50, verbose_name='Текст О нас')),
                ('about_image', models.ImageField(upload_to='static/img/first-screen', verbose_name='Картинка О нас')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
    ]
