# Generated by Django 4.0.3 on 2022-05-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=models.TextField(max_length=50, verbose_name='Текст О нас'),
        ),
    ]
