# Generated by Django 4.0.3 on 2022-05-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pref_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pref_slider',
            name='pref_slider_text',
            field=models.TextField(max_length=10000, verbose_name='Текст слайда'),
        ),
    ]
