# Generated by Django 4.0.3 on 2022-05-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_pref_slider_pref_slider_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_name', models.CharField(max_length=50, verbose_name='Должность и имя')),
                ('reviews_text', models.TextField(max_length=10000, verbose_name='Текст отзыва')),
                ('reviews_where', models.TextField(max_length=10000, verbose_name='Откуда сделан отзыв')),
                ('pref_slider_image', models.ImageField(upload_to='static/img/first-screen', verbose_name='Картинка отзыва')),
            ],
            options={
                'verbose_name': 'Слайд преимущества',
                'verbose_name_plural': 'Слайды преимущества',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(upload_to='static/img/about', verbose_name='Картинка О нас'),
        ),
        migrations.AlterField(
            model_name='pref_slider',
            name='pref_slider_image',
            field=models.ImageField(upload_to='static/img/our-benefits', verbose_name='Картинка слайда'),
        ),
    ]
