# Generated by Django 4.0.3 on 2022-05-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_reviews_pref_slider_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
