# Generated by Django 4.0.3 on 2022-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_pref_slider_image_reviews_reviews_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_cat', models.CharField(max_length=50, verbose_name='Категория вопроса')),
                ('q_title', models.TextField(max_length=50, verbose_name='Заголовок вопроса')),
                ('q_text', models.TextField(max_length=5000, verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
