# Generated by Django 4.0.3 on 2022-05-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_main_slider_main_slider_text_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_slider',
            old_name='main_slider_text_kz',
            new_name='main_slider_text_kk',
        ),
        migrations.RenameField(
            model_name='main_slider',
            old_name='main_slider_title_kz',
            new_name='main_slider_title_kk',
        ),
        migrations.AddField(
            model_name='main_slider',
            name='main_slider_image_en',
            field=models.ImageField(null=True, upload_to='static/img/first-screen', verbose_name='Картинка слайда'),
        ),
        migrations.AddField(
            model_name='main_slider',
            name='main_slider_image_kk',
            field=models.ImageField(null=True, upload_to='static/img/first-screen', verbose_name='Картинка слайда'),
        ),
        migrations.AddField(
            model_name='main_slider',
            name='main_slider_image_ru',
            field=models.ImageField(null=True, upload_to='static/img/first-screen', verbose_name='Картинка слайда'),
        ),
    ]
