# Generated by Django 4.0.3 on 2022-05-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_main_slider_text_kz_main_slider_main_slider_text_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image_en',
            field=models.ImageField(null=True, upload_to='static/img/about', verbose_name='Картинка О нас'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_image_kk',
            field=models.ImageField(null=True, upload_to='static/img/about', verbose_name='Картинка О нас'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_image_ru',
            field=models.ImageField(null=True, upload_to='static/img/about', verbose_name='Картинка О нас'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_text_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст О нас'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_text_kk',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст О нас'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_text_ru',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст О нас'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок О нас'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_title_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок О нас'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок О нас'),
        ),
    ]
