# Generated by Django 4.0.3 on 2022-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_about_about_image_en_about_about_image_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pref_slider',
            name='pref_title',
            field=models.CharField(default='Наши преимущества', max_length=100, verbose_name='Заголовок блока'),
        ),
    ]
