# Generated by Django 4.0.3 on 2022-05-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_pref_slider_pref_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_title', models.CharField(max_length=100, verbose_name='Заголовок блока')),
            ],
            options={
                'verbose_name': 'Заголовок блока Преимущества',
                'verbose_name_plural': 'Заголовок блока',
            },
        ),
    ]
