# Generated by Django 4.0.3 on 2022-05-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_pref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pref',
            options={'verbose_name': 'Заголовок блока Преимущества', 'verbose_name_plural': 'Заголовок блока Преимущества'},
        ),
        migrations.AddField(
            model_name='pref',
            name='pref_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AddField(
            model_name='pref',
            name='pref_title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AddField(
            model_name='pref',
            name='pref_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_image_en',
            field=models.ImageField(null=True, upload_to='static/img/our-benefits', verbose_name='Картинка слайда'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_image_kk',
            field=models.ImageField(null=True, upload_to='static/img/our-benefits', verbose_name='Картинка слайда'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_image_ru',
            field=models.ImageField(null=True, upload_to='static/img/our-benefits', verbose_name='Картинка слайда'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_text_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст слайда'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_text_kk',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст слайда'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_text_ru',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст слайда'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок слайда'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_title_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок слайда'),
        ),
        migrations.AddField(
            model_name='pref_slider',
            name='pref_slider_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок слайда'),
        ),
    ]
