# Generated by Django 4.0.3 on 2022-05-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_questions_q_cat_en_questions_q_cat_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок блока')),
            ],
            options={
                'verbose_name': 'Заголовок блока FAQ',
                'verbose_name_plural': 'Заголовок блока FAQ',
            },
        ),
    ]
