# Generated by Django 4.0.3 on 2022-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_questions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_title',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AddField(
            model_name='questions_title',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AddField(
            model_name='questions_title',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока'),
        ),
    ]
