# Generated by Django 4.0.3 on 2022-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_questions_title_title_en_questions_title_title_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок блока')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок блока')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок блока')),
                ('title_kk', models.CharField(max_length=100, null=True, verbose_name='Заголовок блока')),
            ],
            options={
                'verbose_name': 'Заголовок блока Отзывы',
                'verbose_name_plural': 'Заголовок блока Отзывы',
            },
        ),
    ]
