# Generated by Django 4.0.3 on 2022-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_reviews_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviews_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность и имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность и имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность и имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_text_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_text_kk',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_text_ru',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_where_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='Откуда сделан отзыв'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_where_kk',
            field=models.TextField(max_length=10000, null=True, verbose_name='Откуда сделан отзыв'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_where_ru',
            field=models.TextField(max_length=10000, null=True, verbose_name='Откуда сделан отзыв'),
        ),
    ]
