# Generated by Django 4.0.3 on 2022-05-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_reviews_reviews_name_en_reviews_reviews_name_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_name_en',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_name_kk',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_name_ru',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_text_en',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_text_kk',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_text_ru',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_where_en',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_where_kk',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_where_ru',
        ),
    ]
