# Generated by Django 4.0.3 on 2022-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_reviews_reviews_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=50, verbose_name='Телефон в формате + 7 (777) 777-77-77')),
                ('tel_href', models.CharField(max_length=50, verbose_name='Телефон в формате +77777777777')),
                ('insta_name', models.TextField(max_length=100, verbose_name='Инстаграм подпись')),
                ('insta_name_ru', models.TextField(max_length=100, null=True, verbose_name='Инстаграм подпись')),
                ('insta_name_en', models.TextField(max_length=100, null=True, verbose_name='Инстаграм подпись')),
                ('insta_name_kk', models.TextField(max_length=100, null=True, verbose_name='Инстаграм подпись')),
                ('insta_link', models.TextField(max_length=100, verbose_name='Инстаграм ссылка')),
                ('telegram_name', models.TextField(max_length=100, verbose_name='Телеграмм подпись')),
                ('telegram_name_ru', models.TextField(max_length=100, null=True, verbose_name='Телеграмм подпись')),
                ('telegram_name_en', models.TextField(max_length=100, null=True, verbose_name='Телеграмм подпись')),
                ('telegram_name_kk', models.TextField(max_length=100, null=True, verbose_name='Телеграмм подпись')),
                ('telegram_link', models.TextField(max_length=100, verbose_name='Телеграмм ссылка')),
                ('whatsapp_name', models.TextField(max_length=100, verbose_name='Whatsapp подпись')),
                ('whatsapp_name_ru', models.TextField(max_length=100, null=True, verbose_name='Whatsapp подпись')),
                ('whatsapp_name_en', models.TextField(max_length=100, null=True, verbose_name='Whatsapp подпись')),
                ('whatsapp_name_kk', models.TextField(max_length=100, null=True, verbose_name='Whatsapp подпись')),
            ],
            options={
                'verbose_name': 'Общие настройки по сайту',
                'verbose_name_plural': 'Общие настройки по сайту',
            },
        ),
    ]
