# Generated by Django 4.0.3 on 2022-05-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='insta_name_en',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='insta_name_kk',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='insta_name_ru',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='telegram_name_en',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='telegram_name_kk',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='telegram_name_ru',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='whatsapp_name_en',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='whatsapp_name_kk',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='whatsapp_name_ru',
        ),
    ]
